version: "3.9"
services:
  container:
    build: .
    ports:
      - "9393:9300"
  infracloud:
    image: "infracloudio/csvserver:latest"
    stdin_open: true
    tty: true
    command: bash
    volumes:
      - "./inputFile.txt:/home/docker/data"
      