version: "2.0"
services:
  container:
    build: .
    ports:
      - "9393:9300"
  infracloud:
    image: "infracloudio/csvserver:latest"
    stdin_open: true
    tty: true
    command: bash
    volumes:
      - "./inputFile.txt:/home/docker/data"
prometheus:
  image: prom/prometheus:v2.22.0
  volumes:
    - ./prometheus.yml:/etc/prometheus/prometheus.yml
  ports:
    - "9090:9090"
      